coverage:
  status:
    patch:
      default:
        target: 90%  # Sets patch coverage threshold at 90%
    project:
      default:
        target: 95%  # Optional: sets project-wide coverage target at 95%
